export type BookingStatus =
  | "confirmed"
  | "pending"
  | "rescheduled"
  | "rejected";

export type BookingMethod = "video" | "phone" | "in-person";

export type Booking = {
  id: string;
  name: string;
  phone: string;
  email: string;
  location: string;
  date: string;
  time: string;
  projectType: string;
  budget: string;
  bookingMethod: BookingMethod;
  status: BookingStatus;
};

export const bookings: Booking[] = [
  {
    id: "BK-001",
    name: "James Anderson",
    phone: "(214) 555-0182",
    email: "james.anderson@example.com",
    location: "Dallas, TX",
    date: "2026-09-21",
    time: "10:00 AM",
    projectType: "home-addition",
    budget: "100k-250k",
    bookingMethod: "video",
    status: "confirmed",
  },
  {
    id: "BK-002",
    name: "Emily Carter",
    phone: "(469) 555-0127",
    email: "emily.carter@example.com",
    location: "Plano, TX",
    date: "2026-09-21",
    time: "11:30 AM",
    projectType: "kitchen-remodeling",
    budget: "50k-100k",
    bookingMethod: "phone",
    status: "pending",
  },
  {
    id: "BK-003",
    name: "Michael Thompson",
    phone: "(972) 555-0148",
    email: "michael.thompson@example.com",
    location: "Frisco, TX",
    date: "2026-09-22",
    time: "9:00 AM",
    projectType: "whole-home-remodel",
    budget: "250k-plus",
    bookingMethod: "in-person",
    status: "confirmed",
  },
  {
    id: "BK-004",
    name: "Sarah Mitchell",
    phone: "(817) 555-0193",
    email: "sarah.mitchell@example.com",
    location: "Fort Worth, TX",
    date: "2026-09-22",
    time: "1:00 PM",
    projectType: "bathroom-renovation",
    budget: "50k-100k",
    bookingMethod: "video",
    status: "rescheduled",
  },
  {
    id: "BK-005",
    name: "David Wilson",
    phone: "(214) 555-0164",
    email: "david.wilson@example.com",
    location: "Irving, TX",
    date: "2026-09-23",
    time: "2:30 PM",
    projectType: "roof-repair",
    budget: "under-50k",
    bookingMethod: "phone",
    status: "confirmed",
  },
  {
    id: "BK-006",
    name: "Jessica Brown",
    phone: "(972) 555-0115",
    email: "jessica.brown@example.com",
    location: "McKinney, TX",
    date: "2026-09-23",
    time: "10:30 AM",
    projectType: "consultation-on-site",
    budget: "under-50k",
    bookingMethod: "in-person",
    status: "pending",
  },
  {
    id: "BK-007",
    name: "Robert Davis",
    phone: "(469) 555-0176",
    email: "robert.davis@example.com",
    location: "Allen, TX",
    date: "2026-09-24",
    time: "9:30 AM",
    projectType: "home-addition",
    budget: "100k-250k",
    bookingMethod: "video",
    status: "confirmed",
  },
  {
    id: "BK-008",
    name: "Amanda Martinez",
    phone: "(214) 555-0139",
    email: "amanda.martinez@example.com",
    location: "Richardson, TX",
    date: "2026-09-24",
    time: "3:00 PM",
    projectType: "kitchen-remodeling",
    budget: "50k-100k",
    bookingMethod: "phone",
    status: "rejected",
  },
  {
    id: "BK-009",
    name: "Christopher Garcia",
    phone: "(817) 555-0152",
    email: "christopher.garcia@example.com",
    location: "Arlington, TX",
    date: "2026-09-25",
    time: "11:00 AM",
    projectType: "whole-home-remodel",
    budget: "250k-plus",
    bookingMethod: "in-person",
    status: "confirmed",
  },
  {
    id: "BK-010",
    name: "Ashley Rodriguez",
    phone: "(469) 555-0187",
    email: "ashley.rodriguez@example.com",
    location: "Carrollton, TX",
    date: "2026-09-25",
    time: "1:30 PM",
    projectType: "bathroom-renovation",
    budget: "50k-100k",
    bookingMethod: "video",
    status: "pending",
  },
  {
    id: "BK-011",
    name: "Matthew Lewis",
    phone: "(214) 555-0198",
    email: "matthew.lewis@example.com",
    location: "Denton, TX",
    date: "2026-09-26",
    time: "10:00 AM",
    projectType: "roof-repair",
    budget: "under-50k",
    bookingMethod: "phone",
    status: "confirmed",
  },
  {
    id: "BK-012",
    name: "Stephanie Walker",
    phone: "(972) 555-0161",
    email: "stephanie.walker@example.com",
    location: "Prosper, TX",
    date: "2026-09-26",
    time: "2:00 PM",
    projectType: "home-addition",
    budget: "100k-250k",
    bookingMethod: "in-person",
    status: "rescheduled",
  },
  {
    id: "BK-013",
    name: "Daniel Hall",
    phone: "(469) 555-0108",
    email: "daniel.hall@example.com",
    location: "Grapevine, TX",
    date: "2026-09-27",
    time: "9:00 AM",
    projectType: "kitchen-remodeling",
    budget: "100k-250k",
    bookingMethod: "video",
    status: "confirmed",
  },
  {
    id: "BK-014",
    name: "Lauren Allen",
    phone: "(817) 555-0124",
    email: "lauren.allen@example.com",
    location: "Southlake, TX",
    date: "2026-09-27",
    time: "11:30 AM",
    projectType: "bathroom-renovation",
    budget: "50k-100k",
    bookingMethod: "phone",
    status: "pending",
  },
  {
    id: "BK-015",
    name: "Joseph Young",
    phone: "(214) 555-0171",
    email: "joseph.young@example.com",
    location: "Mesquite, TX",
    date: "2026-09-28",
    time: "1:00 PM",
    projectType: "consultation-on-site",
    budget: "under-50k",
    bookingMethod: "in-person",
    status: "confirmed",
  },
  {
    id: "BK-016",
    name: "Megan Hernandez",
    phone: "(972) 555-0189",
    email: "megan.hernandez@example.com",
    location: "Garland, TX",
    date: "2026-09-28",
    time: "3:30 PM",
    projectType: "whole-home-remodel",
    budget: "250k-plus",
    bookingMethod: "video",
    status: "rejected",
  },
  {
    id: "BK-017",
    name: "Andrew King",
    phone: "(469) 555-0157",
    email: "andrew.king@example.com",
    location: "Little Elm, TX",
    date: "2026-09-29",
    time: "10:30 AM",
    projectType: "home-addition",
    budget: "100k-250k",
    bookingMethod: "phone",
    status: "confirmed",
  },
  {
    id: "BK-018",
    name: "Rachel Wright",
    phone: "(214) 555-0136",
    email: "rachel.wright@example.com",
    location: "Dallas, TX",
    date: "2026-09-29",
    time: "12:00 PM",
    projectType: "kitchen-remodeling",
    budget: "50k-100k",
    bookingMethod: "video",
    status: "pending",
  },
  {
    id: "BK-019",
    name: "Joshua Lopez",
    phone: "(817) 555-0168",
    email: "joshua.lopez@example.com",
    location: "Fort Worth, TX",
    date: "2026-09-30",
    time: "9:30 AM",
    projectType: "roof-repair",
    budget: "under-50k",
    bookingMethod: "in-person",
    status: "confirmed",
  },
  {
    id: "BK-020",
    name: "Nicole Hill",
    phone: "(469) 555-0112",
    email: "nicole.hill@example.com",
    location: "Plano, TX",
    date: "2026-09-30",
    time: "2:30 PM",
    projectType: "bathroom-renovation",
    budget: "50k-100k",
    bookingMethod: "phone",
    status: "rescheduled",
  },
  {
    id: "BK-021",
    name: "Ryan Scott",
    phone: "(972) 555-0143",
    email: "ryan.scott@example.com",
    location: "Frisco, TX",
    date: "2026-10-01",
    time: "10:00 AM",
    projectType: "whole-home-remodel",
    budget: "250k-plus",
    bookingMethod: "video",
    status: "confirmed",
  },
  {
    id: "BK-022",
    name: "Elizabeth Green",
    phone: "(214) 555-0184",
    email: "elizabeth.green@example.com",
    location: "Irving, TX",
    date: "2026-10-01",
    time: "1:30 PM",
    projectType: "home-addition",
    budget: "100k-250k",
    bookingMethod: "in-person",
    status: "pending",
  },
  {
    id: "BK-023",
    name: "Kevin Adams",
    phone: "(817) 555-0191",
    email: "kevin.adams@example.com",
    location: "Arlington, TX",
    date: "2026-10-02",
    time: "11:00 AM",
    projectType: "kitchen-remodeling",
    budget: "100k-250k",
    bookingMethod: "phone",
    status: "confirmed",
  },
  {
    id: "BK-024",
    name: "Michelle Baker",
    phone: "(469) 555-0173",
    email: "michelle.baker@example.com",
    location: "McKinney, TX",
    date: "2026-10-02",
    time: "3:00 PM",
    projectType: "consultation-on-site",
    budget: "under-50k",
    bookingMethod: "in-person",
    status: "rejected",
  },
  {
    id: "BK-025",
    name: "Brian Nelson",
    phone: "(972) 555-0106",
    email: "brian.nelson@example.com",
    location: "Allen, TX",
    date: "2026-10-03",
    time: "9:00 AM",
    projectType: "roof-repair",
    budget: "under-50k",
    bookingMethod: "video",
    status: "confirmed",
  },
  {
    id: "BK-026",
    name: "Heather Carter",
    phone: "(214) 555-0159",
    email: "heather.carter@example.com",
    location: "Richardson, TX",
    date: "2026-10-03",
    time: "12:30 PM",
    projectType: "bathroom-renovation",
    budget: "50k-100k",
    bookingMethod: "phone",
    status: "pending",
  },
  {
    id: "BK-027",
    name: "Jason Roberts",
    phone: "(817) 555-0131",
    email: "jason.roberts@example.com",
    location: "Denton, TX",
    date: "2026-10-04",
    time: "10:30 AM",
    projectType: "whole-home-remodel",
    budget: "250k-plus",
    bookingMethod: "video",
    status: "confirmed",
  },
  {
    id: "BK-028",
    name: "Samantha Turner",
    phone: "(469) 555-0196",
    email: "samantha.turner@example.com",
    location: "Carrollton, TX",
    date: "2026-10-04",
    time: "2:00 PM",
    projectType: "home-addition",
    budget: "100k-250k",
    bookingMethod: "in-person",
    status: "rescheduled",
  },
  {
    id: "BK-029",
    name: "Thomas Phillips",
    phone: "(214) 555-0129",
    email: "thomas.phillips@example.com",
    location: "Grapevine, TX",
    date: "2026-10-05",
    time: "11:30 AM",
    projectType: "kitchen-remodeling",
    budget: "50k-100k",
    bookingMethod: "phone",
    status: "confirmed",
  },
  {
    id: "BK-030",
    name: "Jennifer Campbell",
    phone: "(972) 555-0165",
    email: "jennifer.campbell@example.com",
    location: "Prosper, TX",
    date: "2026-10-05",
    time: "3:30 PM",
    projectType: "consultation-on-site",
    budget: "under-50k",
    bookingMethod: "video",
    status: "pending",
  },
];
